### ISSUE TITLE
indexのサムネイルの幅を狭める

### ISSUE THREAD

**Issue by oosugi20** [pxgrid/ui-spec-md#12]
- index.mdで右側に目次とか書いた方が階層保てて分かりやすい
- そうすると右側が改行しがち
- サムネイル自体小さくするとかして右枠の幅を広げたい

**Comment by leaysgur** [comment]
#6 とおなじ

**Comment by tomof** [comment]
v0.3へのアップデートでタイル表示を辞めたのでクローズします
