### ISSUE TITLE
画像のmax-width

### ISSUE THREAD

**Issue by leaysgur** [pxgrid/ui-spec-md#3]
100%にしたい。
でかい画像だと飛び出る

**Comment by leaysgur** [comment]
人によってサイズ違ってもあれなので、min-width = max-width = 100%で良い気がしてきた

**Comment by yomotsu** [comment]
とりあえず max-width: 100% を入れました。min-widthはどうしよう

https://github.com/pxgrid/ui-spec-md/commit/71564332caac9094a8da40307e571a2f249caa65#diff-bc0edfc289b377520240f2ce622aa161

**Comment by geckotang** [comment]
> min-width = max-width = 100%

width:100%; ...

**Comment by yomotsu** [comment]
`max-width`以外は、アイコンみたいな小さい画像断片も大きくなっちゃって見づらいかなって

**Comment by leaysgur** [comment]
人によって画面解像度とか違って、同じボタンをキャプったはずやのに画像サイズが違ったりするので、固定にしたいなーという気持ち。

アイコンも大きく見えてそれはそれで見やすかったりしますよｗ

**Comment by yomotsu** [comment]
table (shrimp-to-fix)との相性でやはりmax-widthはつらそうなため保留することにしました。
