### ISSUE TITLE
クリップボードから画像を貼り付けたときに名前をつけないとundefined.pngになってしまう

### ISSUE THREAD

**Issue by geckotang** [pxgrid/ui-spec-md#48]
ブラウザ上のテキストエリアで編集中に、クリップボードに画像を入れた状態でペーストすると、
ダイアログが表示されファイル名を入れることになります。

デフォルトが `undefined.png` なのですが、esaのようにユニークなidを振ってあると良いのかなと思いました。（複数貼り付けた場合undefined.pngが上書きされてしまうというのもある）

ただ、コミットするファイルになる想定だとは思うので、ファイル名の指定を必須にするという手もあるかなと思いました。

**Comment by tomof** [comment]
ひとまず、このような実装にして対応しました。#85
また、実際の使い勝手を確認しながら、必要があれば改修していきたいと思います。
