### ISSUE TITLE
generateしたhtmlをそのままブラウザで file: で開けるようにする

### ISSUE THREAD

**Issue by oosugi20** [pxgrid/ui-spec-md#49]
吐き出したhtml等のコード一式を、そのままブラウザで `file:` で開けるようにしたい。

これは、必ずしもuispecをおけるサーバーを設置できたり、見せたい相手がnpmやローカルサーバーを使えるとは限らなかったり、「成果物の納品」としてuispecを渡すケースがあるため。

zipでまとめて相手に渡し、「index.htmlをブラウザにドラッグで開いてください」と伝えるような使い方を想定。

-  `file:` で開ければ、zip化する機能まではuispecになくても良さそう
- generateはすでにできるが、少なくとも相対パスで吐き出す機能は対応が必要そう
- Edit機能などはなくてよい

**Comment by tomof** [comment]
@oosugi20 `0.4.0`にて対応しました。
パスを全て相対パスにするには、`generate`サブコマンドに`-l`オプションを付けてください。

デフォルトテーマの場合
```
ui-spec-md generate -m ./md -d dist/public -l
```
standardテーマの場合
```
ui-spec-md generate -m ./md -d dist/public -t theme/standard -l
```

また、`file:`は現在のモダンブラウザではセキュリティ上の観点から普通に見ることが出来ません。
これはIE11で使われる想定でしょうか？
デフォルトテーマはIE11は切り捨てているため、デフォルトテーマで閲覧することは出来ません。
standardテーマであれば閲覧可能ですが、レイアウトやJS機能が貧弱です。
その辺りの対応が必要な場合は別途issue立てをお願いします。

**Comment by geckotang** [comment]
lオプションつけて、standardテーマにしたら、生成したディレクトリをブラウザにD&Dして、 `file://` で見ることができました。 

デフォルトのテーマだと、 `tree.json` をxhrで取ってくるところが、CORSに引っかかっているためエラーが出て、uispecをみることができません。

なので、 とりあえず `file://` でみたいのであれば「lオプションつけて相対パスにし、standardテーマで生成する」方法でやるとよさそう。

ただ、そうなるとfileで見るためにはlオプションかつstandardテーマにしないといけないので、更にtree.jsonをxhrしない方法を考えてもらうのが良いかもしれない。

おまけでいうとstandardテーマのリンク色が通常の文字色と同じなので何がリンクかわからないという別の問題があった。

**Comment by oosugi20** [comment]
- リンク色は直した方が良さそう
- lオプション付きにしたらstandardテーマにしちゃってもよさそう

**Comment by tomof** [comment]
> lオプション付きにしたらstandardテーマにしちゃってもよさそう

`l`オプションはあくまでローカル閲覧向けに絶対パスを相対パスに書き換えるという意味だからテーマまで変えてしまうことはしたくないです。

下記のようにpackage.jsonに納品用の定義をして欲しいです。
zip化するなら、ここに更にzip化の処理を `&&` で繋げれば良いですし。

```
  "scripts": {
    "delivery": "ui-spec-md generate -m ./md -d dist/delivery -t theme/standard -l",
  },
```

**Comment by geckotang** [comment]
> lオプションはあくまでローカル閲覧向けに絶対パスを相対パスに書き換えるという意味だからテーマまで変えてしまうことはしたくないです。

わかる...。 

ローカル閲覧できるようにするために、tree.jsonをxhrするのがなくなれば良いのだけど。別issueにしますね。
