### ISSUE TITLE
絞り込みするとなんか残る

### ISSUE THREAD

**Issue by leaysgur** [pxgrid/ui-spec-md#5]
<img width="199" alt="2016-04-25 14 35 29" src="https://cloud.githubusercontent.com/assets/6259812/14774616/fcbb3c44-0af2-11e6-885f-344313146af4.png">

謎の黒点の集合が！

**Comment by yomotsu** [comment]
`overflow:hidden` が効いていなかったのでそこを直して対応しました

**Comment by leaysgur** [comment]
なおってた
