### ISSUE TITLE
クリップボードから画像を貼り付ける際に、名前を入力する欄でCtrl+Vすると、画像が保存されない

### ISSUE THREAD

**Issue by geckotang** [pxgrid/ui-spec-md#50]
## 再現手順

- クリップボードに画像を入れる
- ui-spec-mdの左側のキャプチャがある部分の編集UIを呼び出す
- すでにある画像を削除するなりして、画像をCtrl+Vする
- 名前を入力するダイアログが表示される
- ファイル名を入力する前に、 `適当な文字列` をコピーする
- 文字列の `undefined` 部分に `適当な文字列` をCtrl+Vする
- 画像が保存されない

**Comment by geckotang** [comment]
おそらく、画像をペーストした時のイベントをフックしている部分が、名前を入力するダイアログが出ているときも有効になっているからだと思われる。

**Comment by tomof** [comment]
Epic #81 の一連の対応で修正しました。
