### ISSUE TITLE
mdを編集するテキストエリアをリッチなコードエディタにする

### ISSUE THREAD

**Issue by geckotang** [pxgrid/ui-spec-md#51]
今はただのテキストエリアなので、がっつり編集しようとすると結構面倒。僕はesaの拡張を入れているのである程度は融通がきくのだけれど、そうでない人でも編集がしやすい感じになっていると良さそうに感じた。

コードエディタだと知っているのは

- CodeMirror
- AceEditor

とかだけど、他にいいのかも調査したほうが良さそう。
そういえば、身近なところだと、esaのエディタはけっこう使いやすい。

**Comment by geckotang** [comment]
https://github.com/Microsoft/monaco-editor

**Comment by geckotang** [comment]
esaはCodeMirrorだった。

![image](https://user-images.githubusercontent.com/683965/72413992-72547500-37b4-11ea-9725-4eb5d145e481.png)

**Comment by tomof** [comment]
v0.5.0にてCodeMirrorを実装。
esaという信頼できる実績があるので採用しました。
細かい見た目の調整などは、別途取り組んでいきたいと思います。
