### ISSUE TITLE
見出し単位での編集機能

### ISSUE THREAD

**Issue by geckotang** [pxgrid/ui-spec-md#52]
ページの全部を編集したいというよりは、一部の見出しの内容だけ編集したい。

どうしても、1ページの内容が長くなってしまうことがある。長くなった状態で、mdの後半の方にある一部のテキストを修正したりすることもあったりするのだけど、そこの付近だけ編集できたら楽そう。ただのテキストエリアなので、行番号とかもなく、編集したい箇所を見つけるのが面倒...。

（そもそもただのテキストエリアだからやりづらいというのがあるけど #51 に話題を分けた）

その機能は、Redmineにある機能。詳しくは下記を参照してください。

[Redmine 1.3新機能紹介: Wikiページの見出し単位での編集](http://blog.redmine.jp/articles/new-feature-1_3/wiki-single-section-edit/)

**Comment by tomof** [comment]
v0.5.9で対応

編集モードの際に見出しhover時に編集アイコンを表示し、クリックするとその見出し単位で編集できるようにしました。
