### ISSUE TITLE
standardテーマのリンク色をわかりやすくする

### ISSUE THREAD

**Issue by geckotang** [pxgrid/ui-spec-md#53]
![image](https://user-images.githubusercontent.com/683965/72771853-8fba9080-3c45-11ea-8131-b95730303cf5.png)

https://github.com/pxgrid/ui-spec-md/issues/49#issuecomment-576492259 で、standardテーマを使ってみたところ、リンクの色が通常の文字の色と同じであることに気づいた。

通常の文字とリンクの区別がつかないので、リンクの色を指定してあげると良さそう。

**Comment by saucer-jp** [comment]
* normal: `#0066FF`
* hover: `#0047B2`

```
text: {
  color: #0066ff;
  text-decoration: none;
}
text:hover {
  color: #0047b2;
  text-decoration: underline;
}
```

**Comment by tomof** [comment]
多分、ここですね。何故、こんなことしちゃったのか謎です。

https://github.com/pxgrid/ui-spec-md/blob/master/theme/standard/assets/css/style/common.scss#L15

**Comment by tomof** [comment]
v0.4.1で修正済み
