### ISSUE TITLE
tree.jsonを非同期で読み込むのをやめる

### ISSUE THREAD

**Issue by geckotang** [pxgrid/ui-spec-md#54]
ローカルでサーバー立てて編集しているときは、tree.jsonの内容がちょいちょい変わるので、xhrするので良いと思います。

ただgenerateしたときは、tree.jsonの内容は変更されないので、tree.jsonの内容を埋め込んでしまってもいいんじゃないかなと思いました。

tree.jsonを非同期で読み込まなくなれば、 `-l` オプションで相対パスにしたものを、  `file://` で見れるようになりそう。

**Comment by tomof** [comment]
この問題は、`theme` 機能で解決できることなので、基盤の`generate`の機能で調整というのは避けたいです。簡単に実装できれば良いんですが、コードがかなり複雑になりそう。どちらかといえば、stadardテーマを充実させる方針でいきたいです。

更にページ数が膨大になった場合にtree.jsonの行数も相当なものになるので、それが各ファイルに埋め込まれるのも避けたいです。

また、あまり特殊な環境下のためにリソースを割いたり、そのためにソースコードが複雑になることは避けたいのでこの提案は却下とさせてください。

**Comment by tomof** [comment]
> あまり特殊な環境下のためにリソースを割いたり

と思っていましたが、意外とサーバー無しで閲覧したいという要望や需要が多いようなのでリオープンします。
