### ISSUE TITLE
`http://localhost:3001/` でブラウザから編集するとindex.htmlのファイルが生成される

### ISSUE THREAD

**Issue by geckotang** [pxgrid/ui-spec-md#57]
## 概要

`npm start` をして http://localhost:3001/ を開き、編集アイコンをクリックし、テキストエリアの内容を書き換えて保存すると、 `uispec/index.html` が生成されます。

## package.jsonの内容

```
  "scripts": {
    "generate": "ui-spec-md generate -m ./uispec -d dist/public",
    "edit-server": "ui-spec-md edit-server -m ./uispec -d dist/edit",
    "build": "npm run generate",
    "start": "npm run edit-server"
  },
```

## 編集前と編集後のディレクトリの変化

http://localhost:3001/ で編集して保存を行う前

```
uispec/
    index.md
package.json
```

http://localhost:3001/ で編集して保存を行った後

```
uispec/
    index.md
    index.html
package.json
```

**Comment by tomof** [comment]
@geckotang 手元で試してみたのですが再現できず…。`v0.4.1`をリリースしたので試して頂いても良いでしょうか？index周りの修正をしたので。

**Comment by geckotang** [comment]
@tomof v0.4.1にしたら治りました！ありがとうございます。
