### ISSUE TITLE
画像のハイライトを編集してリロードせずに本文を編集して保存すると、画像のハイライトで編集したものが消える

### ISSUE THREAD

**Issue by geckotang** [pxgrid/ui-spec-md#59]
## 再現手順

1. 画像のハイライトを編集して保存する
1. 右側の本文を編集して保存する
1. 編集したはずの画像のハイライトが消えている

## 原因

ハイライトを編集した際に、該当するmdファイルのscreenの部分は更新されている。
しかし、右側の本文のscreenの部分は更新されていない（A）。
なので右側の本文を編集して保存すると、Aの状態で上書きされるため、編集したはずのハイライト情報は消えてしまう。

## 対策

いくつか対策はありそう。

1. 画像の編集を保存したら強制的にリロードする
1. 画像の編集を保存したら本文エリアのscreenの部分を同期する
1. 画像の編集を保存したらリロードするように心がける

当面は 3 でやるが、実装コストと相談すると、1の方法が良いかもしれない。

**Comment by tomof** [comment]
v.0.4.4で対応しました
