### ISSUE TITLE
画面増えるとタイル表示の一覧性が悪い問題

### ISSUE THREAD

**Issue by leaysgur** [pxgrid/ui-spec-md#6]
ありがちなタイル・リスト表示切り替えみたいなのつける

or

 サムネのサイズをもう少しちっさく(結局タイトルの文字を読んでる

やっぱリスト表示ほしいめっちゃほしい

**Comment by yomotsu** [comment]
たしかに。全部同じようなサムネイルですよね...とりあえずこのまま...

**Comment by tomof** [comment]
v0.3へのアップデートでタイル表示を辞めたのでクローズします
