### ISSUE TITLE
テキストエリア上で編集しているとdeleteキーが効かなくなる

### ISSUE THREAD

**Issue by geckotang** [pxgrid/ui-spec-md#60]
## 再現手順

どういうタイミングで起きるのかは不明だが、テキストエリア上で編集して保存して〜と、ずっとそこで編集しているとdeleteキーが効かなくなる。

（もしかしたらChrome拡張のせいだったりするかもしれないけど確認はしていない）

## 対策

#51 でリッチエディタを導入したら問題は解決されるかもしれない。

**Comment by tomof** [comment]
自分もたまに発生していて、原因が不明でした。
v0.5.0にてCodeMirrorにしてからは、一度も発生しなくなったので解消されたと思われます。
もし、再現するようなら再度reopenか新規issue作成をお願いします。
