### ISSUE TITLE
新規ファイル作成ボタンを押して遷移するとページがない場合がある

### ISSUE THREAD

**Issue by geckotang** [pxgrid/ui-spec-md#61]
## 再現手順

1. 左上の新規ファイル作成ボタンを押す
1. ファイル名を入れてOKを押す
1. ページ遷移するが404になる

## 原因

mdファイル作成からhtmlファイル作成のタイミングと、ページ遷移のタイミングがズレているため、遷移しても404になる。リロードするとhtmlファイルができているのでページが表示される。

## 対策

ファイル名入力後、オーバーレイのモーダルなローディングを表示して、htmlファイルが作成できたら遷移する。とか...。

**Comment by tomof** [comment]
v0.4.4で対応しました

原因としては、mdファイルの作成に関してはawaitしていたんですが、htmlファイルはmdファイルをchokidarがwatchして作成しているためでした。

htmlファイル作成が完了するまでポーリング処理でawaitし、その後HTTPステータス302を返すようにしました。
