### ISSUE TITLE
srcディレクトリ内でディレクトリを区切るとcss等へのパスがずれる

### ISSUE THREAD

**Issue by oosugi20** [pxgrid/ui-spec-md#7]
https://github.com/pxgrid/ui-spec-md/blob/master/lib/template/src/_template.html#L7-L8 この辺り。

たとえば、 `src/hoge/fuga.md` ってファイルを置いて生成すると、 `<link rel="stylesheet" href="hoge/_template/_template.css">` とかになっちゃう。

（ HTMLは、 `build/hoge/fuga.html` で吐き出される。）

**Comment by yomotsu** [comment]
https://github.com/pxgrid/ui-spec-md/commit/c96c7f445847c17c8921d19dca27a5b8d077279f で解決しました

**Comment by yomotsu** [comment]
v0.1.1 をリリースしました。npm から取得可能です。

**Comment by oosugi20** [comment]
遅くなりましたが、こちらでも動作確認取れました。

**Comment by yomotsu** [comment]
:bow:
