### ISSUE TITLE
サイトヘッダーのデザイン

### ISSUE THREAD

**Issue by tomof** [pxgrid/ui-spec-md#73]
## 概要

Figma等でヘッダーの色や太さ、アイコンの大きさ、各要素の配置場所等のデザインをお願いしたいです。

### 考慮してもらいたい点
- ヘッダーの背景色はプロジェクトのテーマカラーとしたいです
  - 既存のロゴの兼ね合いもありそうですが、ロゴも変える前提で考えてもらっても問題ないです
  - 画面仕様書といういかにもビジネス的なものなので寒色系の色が良いと思っています
- 各要素の配置
  - アイコンやページのタイトルの位置は左右中央など変えてもらっても問題ないです
  - 左隅か右隅、または中央にロゴを入れたいと考えています
- 将来的にユーザーによるヘッダーのカスタマイズを検討
  - 将来的な機能でヘッダー部分のみ、背景色と上述のロゴをプロジェクトやクライアントに合わせて変更できるようにしたいと考えているのでその点も考慮していただきたいです

## 見た目

画面上部の青い背景色のエリア

![image](https://user-images.githubusercontent.com/1369376/80663370-c1f24e80-8ace-11ea-9744-60f1fd516e85.png)

## ヘッダー内に含まれる要素

- サイトツリーを表示するためのアイコン（ボタン）
  - クリックでサイトツリーのダイアログを表示
  - 虫眼鏡のアイコンだが本来はサイトツリーを示すアイコンにしたいと考えています
    - Font Awesomeのフリー版にサイトツリーを示すものが無いので代用しています
    - 有償版やIcoMoonも検討しましたが現状はこのままで良いと思っています
- Homeアイコン（ボタン）
  - クリックで画面仕様書トップへ移動
- ページ新規作成アイコン（ボタン）
  - クリックで新規にページを作るためのダイアログを表示
- ページのタイトル

**Comment by saucer-jp** [comment]
@tomof アイコンについてですが、僕がFont Awesome Proのライセンスを所持しているので、そちらも選択肢に含めて進めますね

**Comment by saucer-jp** [comment]
Font Awesome Pro は、パブリックなプロジェクトだとライセンス的にNGだったので、[Material Design icons](https://material.io/resources/icons/)に切り替えた。

**Comment by saucer-jp** [comment]
ここで作ってる https://www.figma.com/file/YmCMMXRXJkfr5Xh62uu1w3/UI-Spec-md?node-id=30%3A9

**Comment by saucer-jp** [comment]
月をまたぐので閉じる。変更を入れる場合は別途issue作成する。

https://www.figma.com/file/YmCMMXRXJkfr5Xh62uu1w3/UI-Spec-md?node-id=30%3A9

![image](https://user-images.githubusercontent.com/710479/86135783-3cb70480-bb26-11ea-8808-a842fa467af8.png)
