### ISSUE TITLE
画面画像上部のバーのデザイン

### ISSUE THREAD

**Issue by tomof** [pxgrid/ui-spec-md#74]
## 概要

Figma等で色や太さ、アイコンの大きさ、各要素の配置場所等のデザインをお願いしたいと考えてはいるものの、他に比べると重要度は低いと考えていますので、現段階では今のままでも良いかなと思っています

### 考慮してもらいたい点
- Font Awesomeのフリー版を使っているためアイコン表現が貧弱ですが、ひとまずはこのままでも良いかなと思っています
- highlightだけはON/OFFがわかるような見た目にしたいです
- バーの太さはこの画面画像の右側に配置される仕様書ドキュメントの同様のバーの太さにも影響します（#75）

## 見た目

上部の灰色の背景色のエリア

![image](https://user-images.githubusercontent.com/1369376/80669360-3339fd80-8adf-11ea-8ee3-3beef4b97b4b.png)

## バー内に含まれる要素

- 虫眼鏡（＋）、拡大率、虫眼鏡（ー）
  - 画像のズームモード（？）が有効の場合に、使用できる機能です
  - 画像の拡大・縮小をします
- ズーム(？）・フィット(？）モード切り替え
  - フィットモードは画像全体が見えるように中央に配置
  - ズームモードは画像の拡大・縮小が可能になる
- highlight
  - 画像上のハイライトの表示・非表示の切り替え
- 画像・ハイライト編集ダイアログの表示
  - 画像の指定、ハイライトの編集のためのダイアログを表示する

**Comment by saucer-jp** [comment]
ここでつくってる https://www.figma.com/file/YmCMMXRXJkfr5Xh62uu1w3/UI-Spec-md?node-id=30%3A11

**Comment by saucer-jp** [comment]
月をまたぐので閉じる。変更を入れる場合は別途issue作成する。

https://www.figma.com/file/YmCMMXRXJkfr5Xh62uu1w3/UI-Spec-md?node-id=30%3A11

![image](https://user-images.githubusercontent.com/710479/86136094-a0413200-bb26-11ea-9aba-81e08a5abcc1.png)
