### ISSUE TITLE
仕様書ドキュメント上部のバーのデザイン

### ISSUE THREAD

**Issue by tomof** [pxgrid/ui-spec-md#75]
## 概要

Figma等で色や太さ、アイコンの大きさ、各要素の配置場所等のデザインをお願いしたいです。

### 考慮してもらいたい点
- バーの太さはこの画面画像の左側に配置される画面画像の同様のバーの太さにも影響します（#74）
- 今後この部分にパンくずリンクを入れる予定です
  - パンくずを入れた場合、最終更新者・作成者のスペースが無くなるため、このドキュメントの下部に移動することを考えていますが、他に良い配置場所があれば提案をお願いします
  - 最終更新者・作成者の情報を下部に置く場合、合わせてその下部でどのように表示するのかのデザインもお願いしたいです
  - もしくはパンくずはここではない別の場所のほうが良いという意見があれば、提案いただければと思います
- 最終更新者・作成者
  - LastUpdateやCreatedを英語にしていますが特にこだわっていません（日本語にすることも検討中）
- 左端に編集切り替えのアイコンがありますが、右端にしても良いと考えています
  - このアイコンは編集モード時にのみ表示されるので、表示されない場合の考慮もお願いします

## 見た目

上部の灰色の背景色のエリア

![image](https://user-images.githubusercontent.com/1369376/80670959-654d5e80-8ae3-11ea-9a2b-fb74351d6b9d.png)

## バー内に含まれる要素

- 編集アイコン
  - クリックでドキュメントの編集に切り替わります
- 最終更新者・作成者
  - gitの情報から取得した終更新者・作成者を表示します

**Comment by saucer-jp** [comment]
ここでつくってる https://www.figma.com/file/YmCMMXRXJkfr5Xh62uu1w3/UI-Spec-md?node-id=30%3A12

**Comment by saucer-jp** [comment]
月をまたぐので閉じる。変更を入れる場合は別途issue作成する。

https://www.figma.com/file/YmCMMXRXJkfr5Xh62uu1w3/UI-Spec-md?node-id=30%3A12

![image](https://user-images.githubusercontent.com/710479/86136421-0cbc3100-bb27-11ea-9abb-5e609542b1df.png)
