### ISSUE TITLE
仕様書ドキュメントのデザイン

### ISSUE THREAD

**Issue by tomof** [pxgrid/ui-spec-md#78]
## 概要

Figma等で仕様書ドキュメント上の見出しやリスト等のデザインをお願いしたいです。

### 考慮してもらいたい点
- マークダウンによって出力される主要なHTML要素の見た目のデザインをお願いしたいです
  - 見出し1〜6
  - 箇条書きリスト、番号付きリスト
  - リンク
  - テーブル
- 見出しや段落のマージンなどの余白をどれぐらいにするか
- 見出しホバー時に表示されるアイコン
  - ホバー時にアンカーリンク用のアイコン、見出し別編集アイコン（編集モード時のみ）が表示されます
  - これらはアイコンはそのままで良いかなと考えているので、大きさや余白の調整ぐらいの考慮を考えてもらえればいいかなと思っています

![image](https://user-images.githubusercontent.com/1369376/80678633-44423900-8af6-11ea-86b9-2311216672ca.png)

## 見た目

![image](https://user-images.githubusercontent.com/1369376/80678128-4952b880-8af5-11ea-9d48-65f016738140.png)

**Comment by saucer-jp** [comment]
月をまたぐので閉じる。変更を入れる場合は別途issue作成する。

https://www.figma.com/file/YmCMMXRXJkfr5Xh62uu1w3/UI-Spec-md?node-id=30%3A12

![image](https://user-images.githubusercontent.com/710479/86136421-0cbc3100-bb27-11ea-9abb-5e609542b1df.png)
