### ISSUE TITLE
仕様書ドキュメント編集モード時のデザイン

### ISSUE THREAD

**Issue by tomof** [pxgrid/ui-spec-md#79]
## 概要

Figma等で仕様書ドキュメントの編集モード時のツールバーや編集領域等のデザインをお願いしたいです。

### 考慮してもらいたい点
- メタ情報（titleとscreen）の領域は将来的には、別途UIに切り分けることを検討していますが、しばらくはこのままの予定です
- リンクのアイコンが配置されているツールバーは、今後マークダウンエディタ等によくある機能を追加することでアイコンやボタンが増えていく想定です
- 編集領域（行番号とテキストエリアに相当する部分）は、フォントの種類・大きさの調整ぐらいで良いかなと考えています

## 見た目

![image](https://user-images.githubusercontent.com/1369376/80680814-6f2e8c00-8afa-11ea-9706-7f07c40eb563.png)

### 各要素
- 編集・プレビュー切り替えタブ
  - Previewタブを押すとプレビューに切り替わります
  - プレビューの見た目は編集モード前の見た目そのままなので特にデザインするものは無いと考えています
- ツールバー
  - 現状アイコンボタンが1つだけですが、今後増える想定です
- 編集領域
  - 行番号とテキストエリアの領域です
  - [CodeMirror](https://codemirror.net/)を使用しています
- 保存・キャンセルボタン

**Comment by saucer-jp** [comment]
保存ボタンは無しの方針にすることに（逐次自動保存する）。
Slackでの会話 https://pxgrid.slack.com/archives/C10U7HP0X/p1593060862002900

**Comment by saucer-jp** [comment]
保存ボタン、やっぱりありになりそうな予感。
https://pxgrid.slack.com/archives/C10U7HP0X/p1593503677008200

**Comment by saucer-jp** [comment]
月をまたぐので閉じる。変更を入れる場合は別途issue作成する。

https://www.figma.com/file/YmCMMXRXJkfr5Xh62uu1w3/UI-Spec-md?node-id=30%3A12

![image](https://user-images.githubusercontent.com/710479/86136421-0cbc3100-bb27-11ea-9abb-5e609542b1df.png)
