### ISSUE TITLE
その画面を参照している画面のリンクがどこかに出ると良さそう

### ISSUE THREAD

**Issue by geckotang** [pxgrid/ui-spec-md#97]
今は手動で、親ページヘのリンクを張ったり、関連するページのリンクを手動で書いたりしている。

esaにあるように、そのページを参照している画面のリンクなどがあるとそういったものをわざわざ書く必要がなくなりそうだと感じました。

![image](https://user-images.githubusercontent.com/683965/91964295-eba3d680-ed49-11ea-892c-0fec905ca7dd.png)

**Comment by tomof** [comment]
被リンク情報の収集はビルド時間にかなり影響してしまいそうなため、現状は実装予定はありません。
esaと違い、ローカルで頻繁にビルドしたりDBを持つことができないという事情があることを考慮しています。

また、最新版にはリンクを貼るのを手助けするための機能がサポートされています。

<img width="206" alt="スクリーンショット 2020-09-02 20 09 20" src="https://user-images.githubusercontent.com/1369376/91974111-42181180-ed58-11ea-80cd-17c81f57bcb2.png">

**Comment by geckotang** [comment]
なるほど！その機能を使っていなかった。事情わかったので閉じます。
