### ISSUE TITLE
ハイライトを残したまま画像だけ上書きしたい

### ISSUE THREAD

**Issue by geckotang** [pxgrid/ui-spec-md#98]
左側に表示される画像を差し替えたいときに、Delete Imageすると、ハイライトも一緒に消えます。
画像だけを削除して、ハイライトはそのまま残すようなことはできますか？（要は画像だけを上書きしたい）

画像ファイルを直接上書きすればすむのですが、Figmaを使っていると、画面（やUI）の画像をクリップボードに入れて、UI Spec上で貼り付けて使うことが多く、画像ファイルになっていないのです。

今のところは、Figmaから画像をクリップボードに入れて、UI Spec上でDelete Imageして画像を貼り付け、エディタでCtrl+Zなどしてハイライトのパラメータを消される前に戻す。ということをしています。（ので、なんとかなってはいます。）

**Comment by tomof** [comment]
0.5.15 にて対応しました！
